install.packages("readtext")
library(readtext)
require(stringr)

getwd()
setwd("E:/test/")
folderNames=list("spam","non-spam")
fdata= data.frame("id"=0,"text"="SAD","folder"="abc")
index=1
for (folder in folderNames){
  filenames <- list.files(folder, full.names=TRUE)
  for (name in filenames){
    fdata=rbind(fdata,data.frame("id"=index,"text"=readtext(name)$text,"folder"=folder))
    index = index+1
  }
}
fdata=fdata[-1,]
row.names(fdata)=seq(1,nrow(fdata),1)

fdata <- transform(fdata, total.words = str_count(fdata$text,"\\S+"))
fdata <- transform(fdata, total.characters = str_count(fdata$text))
fdata <- transform(fdata, word_freq_make = round((str_count(tolower(fdata$text),"make")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_address = round((str_count(tolower(fdata$text),"address")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_all = round((str_count(tolower(fdata$text),"all")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_3d = round((str_count(tolower(fdata$text),"3d")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_our = round((str_count(tolower(fdata$text),"our")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_over = round((str_count(tolower(fdata$text),"over")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_remove = round((str_count(tolower(fdata$text),"remove")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_internet = round((str_count(tolower(fdata$text),"internet")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_order = round((str_count(tolower(fdata$text),"order")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_mail = round((str_count(tolower(fdata$text),"mail")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_receive = round((str_count(tolower(fdata$text),"receive")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_will = round((str_count(tolower(fdata$text),"will")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_people = round((str_count(tolower(fdata$text),"people")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_report = round((str_count(tolower(fdata$text),"report")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_addresses = round((str_count(tolower(fdata$text),"addresses")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_free = round((str_count(tolower(fdata$text),"free")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_business = round((str_count(tolower(fdata$text),"business")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_email = round((str_count(tolower(fdata$text),"email")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_you = round((str_count(tolower(fdata$text),"you")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_credit = round((str_count(tolower(fdata$text),"credit")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_your = round((str_count(tolower(fdata$text),"your")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_font = round((str_count(tolower(fdata$text),"font")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_000 = round((str_count(tolower(fdata$text),"000")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_money = round((str_count(tolower(fdata$text),"money")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_hp = round((str_count(tolower(fdata$text),"hp")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_hpl = round((str_count(tolower(fdata$text),"hpl")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_george = round((str_count(tolower(fdata$text),"george")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_650 = round((str_count(tolower(fdata$text),"650")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_lab = round((str_count(tolower(fdata$text),"lab")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_labs = round((str_count(tolower(fdata$text),"labs")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_telnet = round((str_count(tolower(fdata$text),"telnet")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_857 = round((str_count(tolower(fdata$text),"857")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_data = round((str_count(tolower(fdata$text),"data")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_415 = round((str_count(tolower(fdata$text),"415")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_85 = round((str_count(tolower(fdata$text),"85")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_technology = round((str_count(tolower(fdata$text),"technology")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_1999 = round((str_count(tolower(fdata$text),"1999")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_parts = round((str_count(tolower(fdata$text),"parts")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_pm = round((str_count(tolower(fdata$text),"pm")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_direct = round((str_count(tolower(fdata$text),"direct")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_cs = round((str_count(tolower(fdata$text),"cs")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_meeting = round((str_count(tolower(fdata$text),"meeting")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_original = round((str_count(tolower(fdata$text),"original")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_project = round((str_count(tolower(fdata$text),"project")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_re = round((str_count(tolower(fdata$text),"re")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_edu = round((str_count(tolower(fdata$text),"edu")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_table = round((str_count(tolower(fdata$text),"table")/fdata$total.words)*100,2))
fdata <- transform(fdata, word_freq_conference = round((str_count(tolower(fdata$text),"conference")/fdata$total.words)*100,2))
fdata <- transform(fdata, char_freq_semi_colon = round((str_count(fdata$text,";")/fdata$total.characters)*100,3))
fdata <- transform(fdata, char_freq_r_bracket = round((str_count(fdata$text,"\\(")/fdata$total.characters)*100,3))
fdata <- transform(fdata, char_freq_s_bracket = round((str_count(fdata$text,"\\[")/fdata$total.characters)*100,3))
fdata <- transform(fdata, char_freq_exclamation = round((str_count(fdata$text,"!")/fdata$total.characters)*100,3))
fdata <- transform(fdata, char_freq_dollar = round((str_count(fdata$text,"$")/fdata$total.characters)*100,3))
fdata <- transform(fdata, char_freq_hash = round((str_count(fdata$text,"#")/fdata$total.characters)*100,3))
fdata <- transform(fdata,capital_run_length_average = sapply(sapply(str_match_all(fdata$text, "[A-Z]{2,}"),str_count),function(x) ifelse(identical(unlist(x), integer(0)),0,mean(x,na.rm = TRUE))))
fdata <- transform(fdata,capital_run_length_longest = sapply(sapply(str_match_all(fdata$text, "[A-Z]{2,}"),str_count),function(x) ifelse(identical(unlist(x), integer(0)),0,max(x,na.rm = TRUE))))
fdata <- transform(fdata,capital_run_length_total = sapply(sapply(str_match_all(fdata$text, "[A-Z]{2,}"),str_count),function(x) ifelse(identical(unlist(x), integer(0)),0,sum(x,na.rm = TRUE))))
fdata$spam = ifelse(fdata$folder=="spam",1,0)

fdata=fdata[,-c(1,2,3,4,5)]

#write.csv(fdata,"sample_op.csv",row.names = FALSE)

# sapply(sapply(str_match_all(fdata$text, "[A-Z]{2,}"),str_count),max)
# 
# test="dsad TAFVSG jxksmx YRFshxbi UONNONONS ijonwdn 32e3nujdn3 342HBUsd asdWUGFUTGD623" 
# 
# str_match_all(test, "[A-Z]{2,}")
# max(sapply(str_match_all(test, "[A-Z]{2,}"),str_count))
# mean(sapply(str_match_all(test, "[A-Z]{2,}"),str_count))
# sum(sapply(str_match_all(test, "[A-Z]{2,}"),str_count))
sapply(sapply(str_match_all(fdata$text, "[A-Z]{2,}"),str_count),function(x) ifelse(identical(unlist(x), integer(0)),0,max(x,na.rm = TRUE)))
